### ISSUE TITLE
Want a fake DS3 controller to be supported.😢

### ISSUE THREAD

**Issue by lkchx123** [ViGEm/DsHidMini#129]
Written in the front: I am a Chinese, this article is translated by Google, there may be some inconsistencies, please understand.😘

I followed the documentation and successfully installed the latest version of DsHidMini and BthPS3. I used Scptoolkit before, and then uninstalled it completely following the documentation. But my controller still does not appear in the list in the DSHMC.exe.😢

![image](https://user-images.githubusercontent.com/46598881/129256698-8a636ee0-5777-42cd-bc89-6be52b368a70.png)

![image](https://user-images.githubusercontent.com/46598881/129257320-2c3d246f-183e-467d-93d9-e8406a70e2cd.png)

As you can see, its name is DS3 Compatible USB Device. Instead of PLAYSTATION(R)3 Controller.😢I add the ‘DS3 Compatible USB Device’ to the list of supported devices on BthPS3 list in Windows Registry. But the same as before.
![image](https://user-images.githubusercontent.com/46598881/129259444-6dbe1daa-5fa4-4d30-be4a-beba5fa95e86.png)

This fake controller can be recognized and work normally with MotioninJoy, ScpToolkit and an Android software Sixaxis Controller. So is there a way to make this controller be recognized by DsHidMini? Is there any way I can try? 

Thanks.😉

**Comment by Kanuan** [comment]
I'm converting this from a Issue to a Discussion thread for now
