### ISSUE TITLE
PS3 controller doesn't connect wirelessly but works fine with shibari and fireshock

### ISSUE THREAD

**Issue by givingthisago** [ViGEm/DsHidMini#131]
I originally used fireshock and shibari to connect my controller wirelessly and it connects flawlessly

I followed the guide extensively and making sure all drivers prior were deleted since they can conflict with DsHidMini when wireless but no go

Just doesn't connect over bluetooth. 

pairs and works fine over USB and everything is fine in dev manager

Reverted back to shibari and just installed fireshock till I can figure out why dshidmini won't work

**Comment by nefarius** [comment]
Thanks for ignoring the issue template, what do you expect us to do now? You provided literally **nothing** of value. Use Discord, the Forums or GitHub Discussions for support requests or related and stay out of the issue tracker with this type of time waster content, thanks.
