### ISSUE TITLE
Add shoulder pressure sliders to GPJ mode

### ISSUE THREAD

**Issue by nefarius** [ViGEm/DsHidMini#17]
As @Kanuan pointed out there's "room" for the two shoulder pressure sliders in GPJ mode on the 1st (Gamepad) top level collection. Adjust packet translation to support them while honouring the axis limits.

**Comment by Kanuan** [comment]
For "keeping code clean" sake, the shoulder pressure sliders that exist, but are out of DInput reach, on the "joypad" part of the multi device should be removed as well

**Comment by nefarius** [comment]
Yep, good catch.
