### ISSUE TITLE
Add important features to DSHMC

### ISSUE THREAD

**Issue by anwar-alsilwy** [ViGEm/DsHidMini#182]
I hope you can Implement these important functions to DSHMC:

1- Disable/Enable Rumble for all controllers.
2- set default global option for ( HID device mode) for all controllers, even the new ones.
3- add ability to reorder assigned players.

**Comment by nefarius** [comment]
- 1. This can't be achieved by the UI alone, needs to introduce an additional setting within the driver, but when done is possible indeed.
- 2. This is not possible in the current design without introduction of some government logic like an always running service that would monitor decide arrival and change settings accordingly. An alternative would be querying a global property on driver startup overriding the default per device setting but that is tricky as an user mode driver has very limited registry access.
- 3. This is not possible.

**Comment by anwar-alsilwy** [comment]
Ok,
But please at least let me know how to disable Rumble, it's so important for me.
Thanks

**Comment by anwar-alsilwy** [comment]
Ok,
But please at least let me know how to disable Rumble, it's so important for me.
Thanks

**Comment by anwar-alsilwy** [comment]
WOW, okay
I really appreciate your hard work.
Cheers.
