### ISSUE TITLE
DShdmini Dead-zone threashold feature request

### ISSUE THREAD

**Issue by mevin19** [ViGEm/DsHidMini#196]
Hi, I Would like to request a feature for DShdmini to implement Dead-zone threashold, just like SCPtoolkit global configuration had. With DShdmini my camera/right stick keeps jittering around on its own. I Understand that steam has feature like this that you can just enable but it just doesn't seem to work at all for me, It actually won't work when playing, also when you enable steam input, it adds more latency which is obviously not great when playing competitively. Anyways I really appricate this project and would love for this feature to be added, thanks for reading!

**Comment by nefarius** [comment]
Sounds reasonable indeed. Before it can become a reality I need to introduce a new way to fetch configuration. Seems like Microsoft hasn't planned a lot of registry access for poor user mode drivers. I'll cook something up in my usual time frame of 4 weeks to 6 months or so 😁

**Comment by mevin19** [comment]
> 

Nice! That is awesome, thank you so much :) ! can't wait to make the permanent switch from SCP to DSHD
