### ISSUE TITLE
Reversed triggers in SXS mode?

### ISSUE THREAD

**Issue by Robinde67** [ViGEm/DsHidMini#204]
Not sure weather the issue is because of the digital trigger buttons or if the trigger axis is reversed, but when using SXS mode and using the trigger axis as input, the trigger register as pressed when fully released (after pressing it once) and remains pressed until pushing down the trigger.

Looking at the configuration settings for the controller, the triggers have two axis, X-rotation and Y-rotation. 
![image](https://user-images.githubusercontent.com/1881499/155521685-b9389b06-48ef-41df-be4e-1b4e7e622008.png)
That's how they look when in idle position. Everything looks visually identical before and after pressing the triggers once.

Not sure if that is the original behavior of the official sixaxis driver, since i can't get them to work at all.

**Comment by nefarius** [comment]
That's how `SIXAXIS.SYS` works 🙂

**Comment by Robinde67** [comment]
So just Sony being weird and keeping the trigger axis but reversed while having a digital trigger button to mess things up? Yup, sounds legit!

**Comment by nefarius** [comment]
I consider this answered then 😉 

Cheers
