### ISSUE TITLE
PS1 controller L2R2 buttons

### ISSUE THREAD

**Issue by peltho** [ViGEm/DsHidMini#251]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

L2 and R2 buttons are not recognized/working at all

### Steps to reproduce
- Launching a game like GTAV
- Try to use L2 and R2 buttons

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Nothing happens

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 
**Software/driver version(s):** 2.2.282.0

### Any other helpful information

The issue was the same with the ScpToolkit so that's why I tried with DsHidMini without success either

**Comment by nefarius** [comment]
This solution doesn't support PS1 controllers and L2 & R2 are clearly working, confirmed by many testers and users repeatedly.
