### ISSUE TITLE
vibration/rumble didn't work with bluetooth but work with usb

### ISSUE THREAD

**Issue by s1davide** [ViGEm/DsHidMini#270]
### Discussed in https://github.com/ViGEm/DsHidMini/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **inibintang** November 19, 2022</sup>
BthPS3 Bluetooth Drivers v2.6.174
DsHidMini Driver v2.2.282

ps3 sixaxis CECHZC2E B1

HID : xinput
</div>

**Comment by nefarius** [comment]
Why do you open an issue when there already exists a discussion? Some crave to get banned for spam...
