### ISSUE TITLE
Motion controls do not work with GTA GInput mods

### ISSUE THREAD

**Issue by Hydra-Spectre** [ViGEm/DsHidMini#278]
### Bug description
The GTA III/VC/SA GInput mods are supposed to allow for SIXAXIS motion controls and pressure-sensitive buttons when using an SCP Driver Package XInput DLL.

### Steps to reproduce
- Install the GInput mod for the GTA games
- Set "EnableSixaxisHack=" to 1
- Set any or all Sixaxis motion steering to 1.
- Place the DsHidMini "XInput1_3.dll" to the root game folder
- Set DsHidMini to use SXS
- Start the game.

**Actual result:** The pressure-sensitive buttons work, but not the SIXAXIS motion controls.
**Expected result:** Both pressure-sensitive buttons and SIXAXIS motion controls are supposed to work. GInput does not work off Cemu-type motion controls, but rather something similar to RPCS3's native SIXAXIS support. DsHidMini supports SIXAXIS in RPCS3, so it must work with GTA GInput as well.

**Comment by nefarius** [comment]
See #217, something that ain't there can't work.
