### ISSUE TITLE
Certain (Lego) games behave strangely in reaction to DsHidMini compared to ScpToolkit

### ISSUE THREAD

**Issue by TheRWS96** [ViGEm/DsHidMini#279]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://vigem.org/Community-Support/
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
It is a bit strange but when trying to use my Dualshock3 controller trough DsHidMini to play the "old" Lego: The Hobbit / Lord of the Rings games the games react strangely to button inputs when in-game, when i try to jump (press X) or try to do quite a few other actions a second player is automatically added (the control setup in the options is also messed up quite a bit), it is incredibly annoying. 

The reason why i am reporting a issue about this here is because when i switched back to using ScpToolkit like i was using when i last played the games (before i reinstalled windows) this issue never occurs and all the controls work as intend.

Seeing as DsHidMini seems to be the successor of ScpToolkit and some people working on this new tool have worked on the old ScpToolkit i thought that it would at least be worth a try to report this issue, of course i understand that this issue is only tangentially related to the project i understand if you (the developers) decide that this is out of scope of the project but i at least wanted to try.

### Steps to reproduce
- On Windows 10 (version 21H2) setup one Dualshock 3 using a wired connection and DsHidMini
- Startup Lego: The Hobbit / Lord of the Rings (other Lego games of the same type may also have the same issue), go trough the menu and start a new game / load up a game.
- Press a few buttons

**Actual result:** The second player should be added all of a sudden and the control configuration in the options menu is also messed up, you can try setting up the control devices correctly and removing the second player but the moment you start playing again (with one player) a second player is added again and the whole problem starts over.
**Expected result:** When the controller is set up to control player one no buttons on said controller should somehow add player two, you should just be able to play the game in single player mode as intended.

### Machine info

**CPU-Architecture:** 64-bit operating system, x64-based processor 
**Windows version:** Windows 10 20H2
**Software/driver version(s):** v2.2.282 DsHidMini

**Comment by nefarius** [comment]
Out of scope as it's documented thoroughly (see #40, [here](https://vigem.org/projects/DsHidMini/FAQ/) and [here](https://vigem.org/projects/DsHidMini/HID-Device-Modes-Explained/)) how and why DSHM operates in the way it does.
