### ISSUE TITLE
Rumble does not work not with cable not through bluetooth

### ISSUE THREAD

**Issue by HalasKYO** [ViGEm/DsHidMini#281]
- [ ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://vigem.org/Community-Support/
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
The ruble function doesn't work with CECHZC2E(A1) in SXS mode. (It works in Xinput mode but there the buttons are mixed up) I tried the "MightyHIDTest" --> It does change the LED to 1, and also rumbles during test, but afterwards no rumble in games nor through Steam test.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Machine info

 i7 2600 32 Gb ram 180Ti
 20H2 Win 10 22 H2
**Software/driver version(s):** 2.2.282.0 (as far as I know the current)

### Any other helpful information
 Earlier I used the SCP toolkit but the bluetooth I also use for keyboard etc, afterwards i foung this as best alternative.

**Comment by nefarius** [comment]
https://vigem.org/projects/BthPS3/About-Controller-Compatibility/
