### ISSUE TITLE
controller  pressing random inputs on its own

### ISSUE THREAD

**Issue by MesutGench** [ViGEm/DsHidMini#295]
I have 2 original Dualshock3s. I can use them comfortably with scptoolkits in a wired way. I downloaded dshidmini because I want to play wirelessly, I made all the settings according to what was said, but when I enter fifa 23, the left analogue plays randomly. What is the solution to this? 
Note: I tried 3 controllers, it is impossible to have a problem with the hardware.

**Comment by nefarius** [comment]
Read the documentation.
