### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MesutGench** [ViGEm/DsHidMini#296]
I read it but it didn't work. Dude my controller is original, there is no problem when I play cyberpunk 2077 or any game, it only happens in FIFA please don't pass me by and help me

              Read the documentation.

_Originally posted by @nefarius in https://github.com/ViGEm/DsHidMini/issues/295#issuecomment-1576600043_

**Comment by nefarius** [comment]
Read the documentation and stop opening new issues for stuff that aren't issues. Use DS4Windows mode on these kind of games, everything is explained in the docs.
