### ISSUE TITLE
Request for LED states reaction to battery level

### ISSUE THREAD

**Issue by Hubert365** [ViGEm/DsHidMini#30]
It would be nice if there was a way for the LEDs to show the battery level on BTH, instead of one LED at a time going from 4 to 1, having all 4 LEDs on for "Full", 3-2-1 on for "High", 2-1 for "Medium" and LED 1 on for "Low" (in particular for DS4 mode with DS4W, so maybe that means DSHM having priority over DS4W for LEDs?). It would be much easier to quickly see the battery level in the dark / from a certain distance / to catch your attention when it's time to plug.

EDIT: Kirian has already made a modification to implement it in a test version (in DS4W with "Blue" set to 255 instead of 0, the "Red" slider moves across the 4 LED states). In my humble opinion this is an elegant solution already as it doesn't interfere at all with existing color values / LED states translations.

**Comment by nefarius** [comment]
Progress, bar graph mode working 😁 

![image](https://user-images.githubusercontent.com/286631/154493933-c02b0f5d-537a-4e6b-9c80-56c229669d16.png)

**Comment by nefarius** [comment]
Preview for charging:

https://user-images.githubusercontent.com/286631/154499682-16145ef4-183f-457e-b3b7-a958288ce0ac.mp4
