### ISSUE TITLE
Rare functions on O, R3 and L2 buttons

### ISSUE THREAD

**Issue by kyddox** [ViGEm/DsHidMini#304]
First, i want to thank you for this amazing work, i love how it works but i'm facing rare actions when i press the O, R3 or L2 buttons i'm not sure if it is a bug or it's a functionality but it is anoying, when i press R3 on screen keyboard from windows appear over the game, when i press L3 it seems like down arrow is permanently pressed and when i press O button something like turbo mode enables in PCSX2 at least when i'm playing super mario world, if it is not a bug, please tell me how to disbale it, i was searched but found nothing.

**Comment by nefarius** [comment]
The driver simply translates, anything else depends on the configuration, please see the vast documentation on the linked docs page.
