### ISSUE TITLE
Request: option to give dshidmini priority over lightbar translation

### ISSUE THREAD

**Issue by Hubert365** [ViGEm/DsHidMini#31]
With DSHM already having a good native LED system to show battery level, alongside a charging animation (that DS4W lacks?), it would be nice to have the option of giving DSHM priority over LED states. It would be easier for users, not having to set up the LEDs in DS4W to show the battery level, and it also seems like DS3 -> DS4 battery translation has some bugs (High in DSHM showing up as 100% in DS4W, see @Kanuan for more information); DSHM using its native battery levels / LEDs would instantly solve that issue.

**Comment by nefarius** [comment]
This can be done, needs to be accompanied by the required settings properties and additional controls in the UI for the user to influence what's best in every particular case.
