### ISSUE TITLE
Request: option to switch between "single" vs "filling" battery level

### ISSUE THREAD

**Issue by Hubert365** [ViGEm/DsHidMini#32]
This is really similar to #30 , but implemented natively in DSHM, with the option to switch between "filling" (all 4 LEDs on = Full, LED 1 on = Low) and the present LED system (LED #4 on = Full, LED #1 = Low).

**Comment by nefarius** [comment]
We now have like 3 different issues all covering the same topic more or less 😉 Please consolidate and properly populate **one** issue with all the details necessary, thanks.
