### ISSUE TITLE
If you want to use your PS3 controller as a Xbox or PS4 Controller, read this

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/DsHidMini#40]
First, know the terms:

- Standard PS3 controller => DualShock 3 (__DS3__)
- Standard PS4 controller emulation => DualShock 4 (__DS4__) emulation
- Xbox 360/Xbox One controller emulation => __XInput__ emulation

## Main info

If your intention is to use your DS3 as a Xbox controller there are 3 methods:
- [**Recommended**] Setting the controller in `DS4Windows` HID Device Mode and using it alongside `Ryochan7's DS4Windows`. Check the [DS4Windows Mode User Guide](https://vigem.org/projects/DsHidMini/DS4-Mode-User-Guide/) for instructions.
- [**On Beta testing**] Setting the controller in `XInput` HID Device Mode
- Setting the controller in `SXS` HID Device Mod and using it on Steam with `Playstation Configuration Support` enabled on its controller settings

For using your controller as a DS4, you need the `DS4Windows Mode` method above (**FOLLOW THE GUIDE! It will NOT emulate a DualShock 4 by itself!**)

![image](https://user-images.githubusercontent.com/24910442/126792605-fd95a84f-c734-4cc6-8808-579f0e5b438f.png)

## Remarks on using the `DS4Windows` HID Device Mode

- Ryochan7's DS4Windows will create/associate a virtual Xbox or DS4 controller when a DS3 in `DS4Windows` HID Device Mode is detected
- Follow the [DS4Windows Mode User Guide](https://vigem.org/projects/DsHidMini/DS4-Mode-User-Guide/) for instructions
- DS4Windows app makes it possible to do all kind of customizations on the fly: remapping buttons/keyboard/mouse, output curves, circular-vs-square sticks, macro sequences, etc

## Remarks on using the `XInput` HID Device Mode

- This mode will present your DS3 directly as a Xbox controller to the system, more-or-less how ScpToolKit worked
- **In Beta testing as of now on DsHidMini v2**
- **A significant number of games do not work well with this mode**. The game may end-up not detecting the controller, detecting 2 controllers instead of one, having wrong button mappings, randomly stop responding for a few seconds etc. If it works well or not can only be known by testing. See more on the known issues [here](https://github.com/ViGEm/DsHidMini/discussions/114)
- There are no remapping or sticks deadzone settings on DsHidMini for now. If you need those features, use the `DS4Windows` mode method

## Remarks on using the `SXS` HID Device Mode

- Steam can detect the controller as an actual DualShock 3 and will then remap it into (usually) a xbox controller for Steam games
- **Requires** Steam's `Playstation Configuration Support` controller option to be enabled
- Non-Steam games can be launched through Steam by adding them to Steam game list as a local/custom game
- Rumble not supported

## Other questions

If you have a question that is ___not___ covered in one of the pages linked above, have a look at the [Community and Support page](https://vigem.org/Community-Support/) on how to properly reach us.

**Comment by Kanuan** [comment]
TO DO: SECTION ABOUT USING OTHER MODES FOR XINPUT / DS4 EMULATION AND EXPLAIN THE DOUBLE INPUT ISSUE THAT MAY ARISE
--------

**Comment by jdgp31** [comment]
Thank you for this pinned post !  It may help others as it did me. Wasn't aware when setting up DsHidMini for my PS3 controller that I needed another program (DS4Windows) to emulate an Xbox 360 controller in game. Working perfectly now,

**Comment by OneCricketeer** [comment]
Anecdotally, my DS3 Controller worked as expected (via Stream controller support) for several hours after uninstalling SCPToolkit and installing this 

Only after unplugging and rebooting did I start experiencing issues in my game where it seems to think the bumper triggers are inverted/permanently pressed down. Windows USB Controller dialog says differently, however. Would also be nice if X and O buttons were actual buttons and not seen as sliders

**Comment by nefarius** [comment]
> Anecdotally, my DS3 Controller worked as expected (via Stream controller support) for several hours after uninstalling SCPToolkit and installing this
> 
> Only after unplugging and rebooting did I start experiencing issues in my game where it seems to think the bumper triggers are inverted/permanently pressed down. Windows USB Controller dialog says differently, however. Would also be nice if X and O buttons were actual buttons and not seen as sliders

Please don't hijack threads and open a Discussion in case there's a reproducible demand for support, thanks.

**Comment by nefarius** [comment]
Closing to clean the issue tracker but leaving it pinned.

**Comment by nefarius** [comment]
@Kanuan can you please edit the first post and update the now dead links, thanks.
