### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by gx240** [ViGEm/DsHidMini#42]
How do you uninstall DsHidMini? I can't find any uninstall directions.

**Comment by nefarius** [comment]
Same way as FireShock, just use Driver Store Explorer. I'll make an uninstall guide later. Thanks for noticing.

**Comment by nefarius** [comment]
[It has made its way into the docs](https://vigem.org/projects/DsHidMini/How-to-Install/#removal) 😃
