### ISSUE TITLE
Still says that there is a newer version available

### ISSUE THREAD

**Issue by johnodon** [ViGEm/DsHidMini#45]
![image](https://user-images.githubusercontent.com/10155674/113439188-0dd10600-93b8-11eb-8cd5-b614b816a6f7.png)

**Comment by nefarius** [comment]
When did you update to this version? Today?

**Comment by johnodon** [comment]
> When did you update to this version? Today?

Yes sir.

**Comment by nefarius** [comment]
Ah that is a bug of my ingenious caching routine 🐛 Please close it, go to `%APPDATA%` in File Explorer and delete the DsHidMini....json file and try again.

**Comment by johnodon** [comment]
That did the trick.  TY

**Comment by nefarius** [comment]
Good to know, I'll remove that "feature" in the next release as it clearly does more harm than help.

**Comment by Kanuan** [comment]
Maybe replace it with a "check if there is a update available" works better?

**Comment by nefarius** [comment]
> Maybe replacing it with a "check if there is a update available" buttons would be better?

Yep, I think that's even better. Gives the user control over when to contact the GitHub API and speeds up application start.

**Comment by nefarius** [comment]
Reopened to stay visible until next official release is published.

**Comment by nefarius** [comment]
Fixed in `v1.2.122`
