### ISSUE TITLE
Controller vibrates on USB using ScpToolkit but does not vibrate with DsHidMini

### ISSUE THREAD

**Issue by AshUchiha** [ViGEm/DsHidMini#5]
Vibrating in Scptoolkit wired : https://streamable.com/g0sgyu

**Comment by nefarius** [comment]
*Might* be related to #4, investigate.

**Comment by nefarius** [comment]
@AshUchiha kindly test `v1.0.50` for us please.

**Comment by AshUchiha** [comment]
Fixed in 1.0.50
