### ISSUE TITLE
Big Motor only rumbles above certain strength value

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/DsHidMini#52]
### Summary

Big Motor (BM) commands sent to the controller have two parameters: duration and strength. The values range from decimal 0 to 255. Regarding rumble strength:

- decimal 0 turns off the BM
- decimal 1 _should_ activate the BM at minimum strength
- decimal 255 activates BM at maximum strength

What actually happens is that the BM is only activated at a value far greater than decimal 1. With a controller Model: CECHZC2M (Date Code: 2D) the minimum value is decimal 64.

### Testing

- If possible, do these tests with the controller connected by bluetooth
- [Set the controller in SXS mode](https://vigem.org/projects/DsHidMini/HID-Device-Modes-Explained/)
- Make sure the controller is not hidden by HidGuardian/HidHide. If the controller is hidden with HidHide you can just open its Configuration Utility, disable the "Enable device hiding" box in the devices tab and then reconnect the controller to make it visible again.
- [Download and extract this archive](https://github.com/ViGEm/DsHidMini/files/6287824/RumbleStrengthTest.zip)
- Run "MightyHIDTest.exe". If it immediately closes then your controller is not in SXS mode or is hidden
- __MAKE SURE TO NOT CLICK INSIDE THE BLACK WINDOW OTHERWISE THE PROGRAM WILL CRASH__. If you need to select the window to write make sure to click on the top of the command window
- Run the test once (write "1" and then ENTER). Your controller should rumble weakly. If it does not, then the minimum value that makes your controller rumble is greater than decimal 64
- Close the command window

Now, to discover what is the minimum strength that makes your controller rumble, we need to edit the `settings.json` file in the extracted folder to vary the strength value. First, let's choose a new strength value. 

If your controller rumbled with decimal 64, then the next lower value is decimal 63. If it didn't rumble then let's go higher with decimal 65

The reason I'm writing "decimal" everywhere is because we will need to use values in hexadecimal. E.g.:  

- decimal 65 is hexadecimal 41
- decimal 64 is hexadecimal 40
- decimal 63 is hexadecimal 3F

So, after choosing the new decimal value you want to test you need to find its hexadecimal representation. You can convert from decimal to hexadecimal by using [this site](https://www.rapidtables.com/convert/number/decimal-to-hex.html) or by looking in the table in the image below, where hexadecimal values are in black and decimal in red:
![this table](https://files.renoise.com/forum/uploads/5358-hexadecimalchart1.png) 

After having chosen the hexadecimal representation of the new test value:
- Open the `settings.json` file with a text editor (windows' notepad is enough, just right click on the `settings.json` file -> Open with -> Choose another app -> Select notepad on the list
- REPLACE the first 2 digits ___AFTER_ THE "7F" AS SHOWN IN THE IMAGE BELOW__ with the new value:
![image](https://user-images.githubusercontent.com/24910442/114302171-4189eb00-9a9e-11eb-93da-f5b561325a39.png)
- Close the notepad and choose to save changes
- Run MightyHIDTest.exe again, choose "1" again
- Check if your controller will rumble
- Keep trying different values until you find the minimum value where the controller rumbles

### Reporting your findings

It would be great if you provided the maximum amount of info regarding your controller and the tests:

- Your controller model, as well as other relevant info (if you could post a photo of the information sticker in the back of your controller it would be great, but it's not a necessity)
- The minimum value that makes your controller rumble (specifiy if the value is in Decimal or hexadecimal. Better yet, inform both)
- A print of your DSHMC tool so it's possible to see the genuine controller check
- [The identification property of your controller](https://github.com/ViGEm/DsHidMini/issues/50). Keep in mind that 1) you need to be on the latest released driver 2) be connected by USB for this info to be available on Windows

### Proposed solution:

Re-scale BM Strength values to the range that actually activates the motor. If the minimum value is not consistent across all devices then include in DSHMC tool a  slider to adjust the minimum value used for the re-scaling function.

**Comment by Kanuan** [comment]
# This is just an example of report. Don't worry about organizing everything perfectly

## Model: CECHZC2M (Date Code: 2D) / Dualshock 3

__Minimum strength value that activates rumble__: decimal 64 = hexadecimal 40

__Identification property on windows (can only be check when connected by USB)__:

```text
00 01 04 00 08 0C 01 02 18 18 18 18 09 0A 10 11 12 13 00 00 00 00 04 00 02 02 02 02 00 00 00 04 04 04 04 00 00 04 00 01 02 07 00 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

### __Genuine?__: Yes

![image](https://user-images.githubusercontent.com/24910442/113928067-a9051980-97c4-11eb-9e0d-67e2f93aac58.png)


## Model: CECHZC2M (Date Code: 3A) / Dualshock 3

__Minimum strength value that activates rumble__: decimal 64 = hexadecimal 40

__Identification property on windows (can only be check when connected by USB)__:

```text
00 01 04 00 09 0C 01 02 18 18 18 18 09 0A 10 11 12 13 00 00 00 00 04 00 02 02 02 02 00 00 00 04 04 04 04 00 00 04 00 01 02 07 00 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

__Genuine?__: Yes

![image](https://user-images.githubusercontent.com/24910442/113927405-d1404880-97c3-11eb-9583-22abad92ef90.png)

**Comment by Hubert365** [comment]
![image](https://user-images.githubusercontent.com/79023565/113948067-0bb4e000-97da-11eb-9e46-1ba0f4d659f9.png)

### Minimum strength value that activates rumble: _`decimal 64 = hexadecimal 40`_

### Model: CECHZC2U / FCC ID:AK8CECHZC2 / IC: 409B-CECHZC2

```text
00 01 04 00 06 0C 01 02 18 18 18 18 09 0A 10 11 12 13 00 00 00 00 04 00 02 02 02 02 00 00 00 04 04 04 04 00 00 04 00 01 02 07 00 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

**Comment by Ghaleon4** [comment]
## Model: CECHZC2U (Date Code: ?) / Dualshock 3
__Minimum strength value that activates rumble__: decimal 64 = hexadecimal 40

Identification property on windows (can only be check when connected by USB):
Not queried yet 

__Genuine?__: NO
![image](https://user-images.githubusercontent.com/44887882/114226822-bbed2a80-9939-11eb-8a8b-19fbbb55e3af.png)
![20210409_133949](https://user-images.githubusercontent.com/44887882/114227082-1d14fe00-993a-11eb-9453-dc0f94092242.jpg)

**Comment by nefarius** [comment]
FYI release `v1.2.122` has the identification packet feature included.

**Comment by Kanuan** [comment]
## CONTROLLER SPECS
Model: CECHZC2U / Dualshock 3
FCC ID: AK8CECHZC2
IC: 409B-CECHZC2

__Minimum strength value that activates rumble:__  couldn't find the exact value, but it is around decimal 84 = hexadecimal 54

__Identification property on windows (can only be check when connected by USB):__
```text
00 01 04 00 06 0C 01 02 18 18 18 18 09 0A 10 11 12 13 00 00 00 00 04 00 02 02 02 02 00 00 00 04 04 04 04 00 00 04 00 01 02 07 00 17 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```


__Genuine?:__ Yes
![image](https://user-images.githubusercontent.com/24910442/117761779-59b86b80-b1fe-11eb-8af9-eaafee75bf39.png)

## Notes

Because this controller's minimum BM rumble strength isn't 0x40, it seems like the option to tweak the minimum value is necessary.
