### ISSUE TITLE
Fake/Copy-cat DS3 controller doesn't connect over Bluetooth

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/DsHidMini#61]
Keep in mind: this is a really specific, rare issue and chances are that if your controller is not connecting by Bluetooth it's probably for another reason. If the issue described here ends up not being your case, [have a look in our Bluetooth connection troubleshooting section](https://vigem.org/projects/DsHidMini/How-to-Install/#troubleshooting).

# The issue

Most fake DS3 controllers work fine over Bluetooth... ___Most___. Some reeeally rare copy-cats controllers don't use encrypted connections on bluetooth. Because Windows sees this as a security hazard it immediately drops the device when it tries to connect. This is something that DsHidMini and BthPS3 can't fix, the only option is to use the controller wired.

# Known controllers with this issue

[DS3 copy-cat identified as _Pro Controller_](https://vigem.org/projects/BthPS3/Amazon-Choice-Pro-Controller/). We have discovered that there are other controllers with different appearances/shells that suffer from the same issue.

# How to check

Before trying this, follow the How to Install article's [_Troubleshooting_](https://vigem.org/projects/DsHidMini/How-to-Install/#troubleshooting) section to be 100% sure DsHidMini is correctly installed, BthPS3 is working, the controller is correctly paired to the current Bluetooth Host address and everything indicates the controller _should_ be connecting, then:

## Adding the `Pro Controller` to the list of supported devices on BthPS3 list

- Press `Win + R` to open the Windows `Run` tool
- On the `Run` Tool, type `regedit` and then press `OK`. Windows' registry editor should open
- Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BthPS3\Parameters`
- On the right side, modify the `SIXAXISSupportedNames` entry
- Add the name `Pro Controller` to the list (best if you copy and paste the name there, it needs to be a exact match)
- Confirm the change and then close Windows Registry

![image](https://user-images.githubusercontent.com/24910442/117216031-7f480e00-add5-11eb-96cb-a0286a6faf09.png)

## Checking Windows Event Viewer

- Try connecting your controller wirelessly
- Press `Win + X` and then open the `Event viewer` on the appearing menu
- Expand the "Warning" section and then double click on the `BTHUSB` source entry:  
![image](https://user-images.githubusercontent.com/24910442/114323328-08339880-9afb-11eb-8e87-f50f2fc6d45f.png)
- Check if there is a __recent__ (look at the time) "warning" entry that has the same General description, `Windows rejected a device connection because the device didn't establish encryption prior to the service level connection`, as shown in the image below:
![image](https://user-images.githubusercontent.com/24910442/114323448-a4f63600-9afb-11eb-9600-8fe2d0373bad.png)

## Results

- If a warning with the same description exists then you are out of luck
- If the warning does not appear on Windows' event log then your controller is probably failing to connect for another reason and requires a BthPS3 tracing to determine exactly why. [Reach us through the proper means](https://vigem.org/Community-Support/) so we can give you a hand

# Working around the issue (TL,DR: You can't)

The only way is fully replacing the whole Windows' Bluetooth Stack with another KMDF bluetooth stack that checks and accepts in-coming, unsecure DS3 connections. __This driver does not exist__ and probably never will since it's a enormous amount of work for little to no benefit (how many people have this _Pro Controller_ DS3 copy-cat?).

**Comment by nefarius** [comment]
[Related important read](https://vigem.org/projects/BthPS3/Amazon-Choice-Pro-Controller/).

**Comment by Kanuan** [comment]
# Known unsupported controllers

## PS III Double Shock Wireless Controller

Besides the amazon one Nef linked above, this `DUALSHOCH` controller from... Wantech Electronics? I think, seems to also use unsecured connections via BT, meaning it also is unsupported by Windows/BthPS3

![image](https://user-images.githubusercontent.com/24910442/118372333-82868b00-b587-11eb-8a3b-5bd62d0443da.png)
![image](https://user-images.githubusercontent.com/24910442/118372320-71d61500-b587-11eb-97f7-5bb73ad356b5.png)

**Comment by Akami23** [comment]
i have a same ds3 controller name pro controller, its connected to laptop wirelessly but its disconnected after 6 seconds.
What is the problem? in the controller or in the dongle?
![Screenshot 2021-07-27 095502](https://user-images.githubusercontent.com/78730392/127087926-91289c7d-a0b7-4966-9b8d-0326e735ed0d.png)

**Comment by nefarius** [comment]
Closed so it disappears from the open issues list but keeping it pinned.
