### ISSUE TITLE
Feature Request: Adjustable Idle Timeout Disconnect

### ISSUE THREAD

**Issue by rjmxtechnology** [ViGEm/DsHidMini#8]
Coming from scptoolkit I feel that a slider in the config utility for setting an idle timeout disconnect period would be helpful. Hopefully it wouldn't be too much of a hassle to add

**Comment by nefarius** [comment]
Moved to the right place.

**Comment by rjmxtechnology** [comment]
No worries, glad to see it is in the works!!

**Comment by rjmxtechnology** [comment]
Somewhat related since you moved the issue, but is there a way to stop windows from detecting the DS3 at the same time as the emulated 360 when using dshidmini with DS4Windows? My games seem to be showing both the xbox and ds3 inputs when I connect a controller

**Comment by nefarius** [comment]
Please open a separate issue since that is a completely different topic 🙂
