### ISSUE TITLE
Vibration not working over bluetooth, but working through usb

### ISSUE THREAD

**Issue by rissei** [ViGEm/DsHidMini#88]
BthPS3 1.3.127.0
DS4windows 3.0.5
Dshidmini v1.4.222.0
Intel wireless bluetooth USB\VID_8087&PID_0A2B&REV_0001

After following the main guide and setting everything up, I noticed, using MightyHIDTest, that the rumble funtion does not work over bluetoth for my ps3 controller, is this a resurgence of #4? also apparently according to Dshidmini my controller is not genuine.
![IMG_20210518_225723_1_2](https://user-images.githubusercontent.com/84419163/118728726-90106f00-b82c-11eb-94a5-7356182ea714.jpg)

**Comment by rissei** [comment]
Umm, hey?, I still have this problem, and need assistance

**Comment by Kanuan** [comment]
Oh, forgot about this. 
It's not related to the issue you linked, that was (supposed to be) fixed for good.
Can you send a screenshot of your DSHMC when connected over BT?
Besides that, join the server's discord so it's easier to test on this

**Comment by rissei** [comment]
Alright, will upload once I get to my laptop, do I send it here or to the discord server?

**Comment by Kanuan** [comment]
send it here to keep it registered, then we continue on the server

**Comment by rissei** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/84419163/119259062-5771ec00-bbc4-11eb-8cac-4f8a43ff21c1.png)
![Screenshot (24)](https://user-images.githubusercontent.com/84419163/119259065-593baf80-bbc4-11eb-96db-72adae462010.png)

Done!
